/* BLUEWATER — a lightweight, self-contained nautical game. */
const canvas=document.getElementById('sea'),ctx=canvas.getContext('2d'),mini=document.getElementById('map'),mc=mini.getContext('2d');
const $=id=>document.getElementById(id),TAU=Math.PI*2,keys={},world=2600,MAX_SPEED=150/1.94384;
const destinations=[
{x:-1750,y:1250,r:245,name:'로토파고이',subtitle:'연꽃 먹는 사람들의 섬',seed:2,color:'#719677',type:'lotus',desc:'고향의 기억을 잊게 하는 연꽃의 섬. 분홍빛 연꽃이 가득한 해안에서 첫 항해 기록을 남기세요.'},
{x:-1700,y:-450,r:280,name:'키클롭스의 섬',subtitle:'폴리페모스의 동굴',seed:3,color:'#857e6e',type:'cave',desc:'외눈박이 거인 폴리페모스의 섬. 바위산과 검은 동굴을 지나 남쪽 정박지로 접근하세요.'},
{x:-250,y:-1650,r:235,name:'아이올리아',subtitle:'바람의 신 아이올로스의 섬',seed:5,color:'#88a59b',type:'wind',desc:'아이올로스가 머무는 바람의 섬. 해안을 감싸는 바람의 고리가 다음 여정을 가리킵니다.'},
{x:1450,y:-1050,r:310,name:'텔레필로스',subtitle:'레스트리곤 식인 거인의 해안',seed:7,color:'#86675e',type:'cliff',desc:'거인들의 돌세례가 함대를 덮친 해안. 붉은 절벽 주변에서는 속력을 줄여 충돌을 피하세요.'},
{x:1600,y:650,r:265,name:'아이아이아',subtitle:'마녀 키르케의 섬',seed:9,color:'#707990',type:'temple',desc:'울창한 숲속에 키르케의 궁전이 숨어 있는 섬. 보랏빛 숲과 신전이 귀향길의 마지막 기착지를 지킵니다.'},
{x:100,y:1700,r:240,name:'이타카',subtitle:'마침내, 고향으로',seed:11,color:'#829267',type:'home',desc:'긴 모험 끝에 돌아온 고향. 앞선 다섯 섬을 방문한 뒤 마지막으로 정박하면 귀향을 마칩니다.'}
];
const islands=[...destinations,{x:-850,y:450,r:135,seed:12},{x:480,y:-480,r:145,seed:13},{x:2050,y:1700,r:110,seed:14}];
const ports=destinations.map(i=>({x:i.x,y:i.y+i.r+120,name:i.name}));
const settings={calm:{wind:4,wave:.3,drift:.3,color:'#0a7187'},windy:{wind:17,wave:1.2,drift:1.8,color:'#17687e'},storm:{wind:32,wave:2.8,drift:4.3,color:'#27586d'}};
let w=innerWidth,h=innerHeight,dpr=1,cam={x:0,y:650},ship,clock=0,elapsed=0,last=0,paused=false,ended=false,visited=0,dock=0,cooldown=0,wakes=[],wakeTimer=0,toastTimer=0,chartOpen=false,chartPreviousPause=false,sceneIndex=-1,homeOpen=true;
function reset(){window.cinema?.stop();window.strait?.reset();$('posterEnd').hidden=true;sceneIndex=-1;$('islandScene').hidden=true;document.body.classList.remove('ashore');chartOpen=false;$('atlas').hidden=true;ship={x:-1900,y:2220,a:0,v:0,hull:100,rudder:0};cam={x:-1900,y:2220};elapsed=0;visited=0;dock=0;paused=homeOpen;ended=false;cooldown=0;wakes=[];$('overlay').hidden=true;$('pause').textContent='Ⅱ';document.querySelectorAll('.route span').forEach((e,i)=>e.className=i===0?'active':'');updateUI();if(!homeOpen)toast('W / ↑ 로 출항하세요. M 키로 오디세이 전체 해도를 펼쳐보세요.');}
function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);}
const scale=()=>w<600?.72:1;
function project(x,y,z=0){return{x:w*.53+(x-cam.x)*scale(),y:h*.52+(y-cam.y)*.70*scale()-z*scale()};}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');toastTimer=5;}
function togglePause(){if(window.strait?.active||sceneIndex>=0)return;if(chartOpen){closeChart();return;}if(ended)return;paused=!paused;Object.keys(keys).forEach(k=>keys[k]=false);$('overlay').hidden=!paused;$('overlayTitle').textContent='항해 일시정지';$('overlayText').textContent='잠시 쉬어가세요. 준비되면 다시 출항할 수 있어요.';$('resume').textContent='항해 계속하기';$('pause').textContent=paused?'▶':'Ⅱ';}
function finish(success){ended=true;paused=true;$('overlay').hidden=false;$('overlayTitle').textContent=success?'이타카에 돌아왔습니다.':'항해를 마쳤습니다';$('overlayText').textContent=success?`여섯 섬의 여정을 완주했어요. 항해 시간 ${Math.floor(elapsed/60)}분 ${Math.floor(elapsed%60)}초 · 선체 ${Math.ceil(ship.hull)}%`:'선체가 손상되었어요. 다음 항해에서는 섬 주변에서 속력을 줄여보세요.';$('resume').textContent='새 항해 시작';}
function step(dt){clock+=dt;if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').classList.remove('show');}if(paused)return;elapsed+=dt;cooldown=Math.max(0,cooldown-dt);const sea=settings[$('weather').value];
const throttle=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0),turn=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0);
ship.v+=throttle*23*dt;ship.v*=Math.exp(-(.095+(keys[' ']?1.7:0))*dt);ship.v=Math.max(-10,Math.min(MAX_SPEED,ship.v));ship.rudder+=(turn-ship.rudder)*Math.min(1,dt*5);ship.a+=ship.rudder*(ship.v/MAX_SPEED)*.95*dt;
ship.x+=(Math.sin(ship.a)*ship.v+sea.drift*.7)*dt;ship.y+=(-Math.cos(ship.a)*ship.v+sea.drift*.3)*dt;
ship.a+=Math.sin(clock*1.1)*sea.wave*.009*dt;
for(const island of islands){let dx=ship.x-island.x,dy=ship.y-island.y,dist=Math.hypot(dx,dy),limit=island.r+17;if(dist<limit){if(dist<.001){dx=1;dy=0;dist=1;}ship.x=island.x+dx/dist*limit;ship.y=island.y+dy/dist*limit;if(cooldown===0){ship.hull=Math.max(0,ship.hull-Math.max(2,Math.abs(ship.v)*.52));toast('해안에 부딪혔어요. 속력을 줄이고 후진해 빠져나오세요.');cooldown=1.5;}ship.v*=-.25;}}
if(Math.abs(ship.x)>world||Math.abs(ship.y)>world){ship.x=Math.max(-world,Math.min(world,ship.x));ship.y=Math.max(-world,Math.min(world,ship.y));ship.v*=-.2;if(cooldown===0){toast('항해 구역의 끝이에요. 해도 안쪽으로 돌아가세요.');cooldown=2;}}
if(ship.hull<=0){finish(false);return;}const p=ports[visited];if(p){let dist=Math.hypot(ship.x-p.x,ship.y-p.y);if(dist<76&&Math.abs(ship.v)*1.94384<3){dock+=dt;$('hint').textContent=`정박 중… ${Math.min(100,Math.floor(dock/2*100))}%`;if(dock>=2){visited++;dock=0;ship.hull=Math.min(100,ship.hull+15);document.querySelectorAll('.route span').forEach((e,i)=>e.className=i<visited?'done':i===visited?'active':'');enterIsland(visited-1);updateUI();return;}}else{dock=0;$('hint').textContent=dist<100?'Space 또는 S로 3노트 이하까지 감속하세요.':'빛나는 원 안에서 3노트 이하로 감속해 정박하세요.';}}
cam.x+=(ship.x-cam.x)*(1-Math.exp(-dt*2));cam.y+=(ship.y-cam.y)*(1-Math.exp(-dt*2));wakeTimer+=dt;if(wakeTimer>.085&&Math.abs(ship.v)>1){wakes.push({x:ship.x-Math.sin(ship.a)*33,y:ship.y+Math.cos(ship.a)*33,a:ship.a,age:0,v:Math.abs(ship.v)});wakeTimer=0;}wakes.forEach(p=>p.age+=dt);wakes=wakes.filter(p=>p.age<6);updateUI();}
function updateUI(){const kn=Math.abs(ship.v)*1.94384;$('speed').textContent=kn.toFixed(1);$('speedBar').style.width=(kn/150*100)+'%';const deg=((ship.a*180/Math.PI)%360+360)%360;$('heading').textContent=Math.round(deg%360).toString().padStart(3,'0');$('direction').textContent=['N · 북','NE · 북동','E · 동','SE · 남동','S · 남','SW · 남서','W · 서','NW · 북서'][Math.round(deg/45)%8];$('hull').textContent=Math.ceil(ship.hull);$('hullBar').style.width=ship.hull+'%';$('hullBar').style.background=ship.hull<35?'#ef947f':'#87c8b4';$('progress').textContent=visited+' / '+ports.length;$('number').textContent=String(Math.min(ports.length,visited+1)).padStart(2,'0');const p=ports[visited];$('portName').textContent=p?p.name:'모든 항구 방문 완료';$('distance').textContent=p?`목적지까지 ${Math.round(Math.hypot(ship.x-p.x,ship.y-p.y))} m`:'항해 완료';}
function poly(points,fill,stroke){ctx.beginPath();points.forEach((p,i)=>{let q=project(p[0],p[1],p[2]||0);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);});ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function ring(x,y,r,color,width=1){const p=project(x,y);ctx.beginPath();ctx.ellipse(p.x,p.y,r*scale(),r*.70*scale(),0,0,TAU);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();ctx.lineWidth=1;}
function islandShape(i,r,z){let pts=[];for(let n=0;n<48;n++){let a=n/48*TAU,f=1-.065*(1+Math.sin(a*5+i.seed))-.03*(1+Math.cos(a*7+i.seed));pts.push([i.x+Math.cos(a)*r*f,i.y+Math.sin(a)*r*f,z]);}return pts;}
function drawIsland(i){poly(islandShape(i,i.r*1.34,0),'#35b6bb30');poly(islandShape(i,i.r*1.18,0),'#65d8ca3c');poly(islandShape(i,i.r*1.07,0),'#addcc270');poly(islandShape(i,i.r,3),'#d7c997');poly(islandShape(i,i.r*.87,10),i.color||'#6c946d');poly(islandShape(i,i.r*.78,18),i.color||'#4e8263');poly(islandShape(i,i.r*.65,27),i.color||'#49785d');
for(let n=0;n<22;n++){let a=n*2.399+i.seed,r=i.r*.66*Math.sqrt((n+1)/23),x=i.x+Math.cos(a)*r,y=i.y+Math.sin(a)*r;poly([[x-4,y+4,20],[x+12,y+8,20],[x+5,y-7,24]],'#335f5255');let p=project(x,y,24);ctx.fillStyle=n%2?'#315d4e':'#386954';ctx.beginPath();ctx.ellipse(p.x,p.y-5,7*scale(),12*scale(),-.2,0,TAU);ctx.fill();ctx.fillStyle='#648566';ctx.beginPath();ctx.ellipse(p.x-2,p.y-9,3*scale(),6*scale(),-.3,0,TAU);ctx.fill();}
drawLandmark(i);
if(i.name){const p=project(i.x,i.y+i.r*.52,3);ctx.font='12px Arial';ctx.textAlign='center';ctx.fillStyle='#edeee1';ctx.fillText(i.name,p.x,p.y);}}
function drawPort(p,i){let active=i===visited;ring(p.x,p.y,76,active?'#f1cd87a0':'#cee9db30',active?2:1);if(active)ring(p.x,p.y,70+Math.sin(clock*2)*5,'#ffe1a23f',4);const q=project(p.x,p.y);ctx.fillStyle=i<visited?'#96dec5':active?'#ffd48a':'#97c4c9';ctx.beginPath();ctx.arc(q.x,q.y,4,0,TAU);ctx.fill();ctx.font='13px Arial';ctx.textAlign='center';ctx.fillText(i<visited?'✓ '+p.name:p.name,q.x,q.y-26);if(active&&dock>0){ctx.beginPath();ctx.ellipse(q.x,q.y,76*scale(),76*.7*scale(),0,-Math.PI/2,-Math.PI/2+TAU*dock/2);ctx.strokeStyle='#fff4bf';ctx.lineWidth=5;ctx.stroke();ctx.lineWidth=1;}}
function drawShip(){const q=project(ship.x,ship.y,4),s=scale(),sea=settings[$('weather').value],roll=Math.sin(clock*2.2)*sea.wave*.025;ctx.save();ctx.translate(q.x,q.y+Math.sin(clock*2.6)*sea.wave*2);ctx.scale(s,s*.70);ctx.rotate(ship.a+roll);
ctx.fillStyle='#002b4155';ctx.beginPath();ctx.ellipse(9,12,17,48,0,0,TAU);ctx.fill();
function hull(offset,color){ctx.beginPath();ctx.moveTo(0,-44+offset);ctx.bezierCurveTo(18,-27+offset,17,15+offset,12,37+offset);ctx.lineTo(-12,37+offset);ctx.bezierCurveTo(-17,15+offset,-18,-27+offset,0,-44+offset);ctx.fillStyle=color;ctx.fill();}hull(5,'#173d50');hull(0,'#ab7346');ctx.strokeStyle='#b8cbd0';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='#d1a576';ctx.fillRect(-10,-25,20,57);ctx.strokeStyle='#724b31';ctx.lineWidth=2;for(let n=-20;n<30;n+=8){ctx.beginPath();ctx.moveTo(-9,n);ctx.lineTo(9,n);ctx.stroke();}for(let n=-14;n<24;n+=9){ctx.beginPath();ctx.moveTo(-12,n);ctx.lineTo(-29,n+9+Math.sin(clock*4)*3);ctx.moveTo(12,n);ctx.lineTo(29,n+9+Math.sin(clock*4)*3);ctx.stroke();}ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,15);ctx.lineTo(0,-30);ctx.stroke();ctx.fillStyle='#f2e1b7';ctx.beginPath();ctx.moveTo(-26,-18);ctx.quadraticCurveTo(0,-6,26,-18);ctx.lineTo(23,6);ctx.quadraticCurveTo(0,18,-23,6);ctx.closePath();ctx.fill();ctx.strokeStyle='#be6d4a';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-1,7,0,TAU);ctx.stroke();ctx.restore();}
function draw(){const sea=settings[$('weather').value];ctx.fillStyle=sea.color;ctx.fillRect(0,0,w,h);let grd=ctx.createRadialGradient(w*.65,h*.30,0,w*.5,h*.5,w*.85);grd.addColorStop(0,'#3aabb326');grd.addColorStop(1,'#002c4d64');ctx.fillStyle=grd;ctx.fillRect(0,0,w,h);
// World-anchored wave crests give motion and distance cues.
let left=Math.floor((cam.x-w/scale())/90)*90,top=Math.floor((cam.y-h/scale())/85)*85;
for(let x=left;x<cam.x+w/scale();x+=90)for(let y=top;y<cam.y+h/scale();y+=85){let phase=x*.018+y*.023,off=Math.sin(phase+clock*.7)*10;let q=project(x+off,y+Math.sin(phase)*28+clock%1000*sea.wave*.6);ctx.strokeStyle=`rgba(157,224,222,${.06+(.5+.5*Math.sin(phase+clock))*.095})`;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(q.x-12,q.y);ctx.quadraticCurveTo(q.x,q.y-4-sea.wave*2,q.x+19,q.y-1);ctx.stroke();}
const target=ports[visited];if(target){const from=project(ship.x,ship.y),to=project(target.x,target.y);ctx.save();ctx.setLineDash([3,12]);ctx.strokeStyle='#f2ce7b35';ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();ctx.restore();}
for(let p of wakes){let q=project(p.x,p.y),alpha=(1-p.age/6)*.24;ctx.save();ctx.translate(q.x,q.y);ctx.scale(scale(),scale()*.70);ctx.rotate(p.a);ctx.strokeStyle=`rgba(216,249,241,${alpha})`;ctx.lineWidth=2;ctx.beginPath();let spread=10+p.age*p.v*.35;ctx.moveTo(-spread,12);ctx.quadraticCurveTo(0,22,spread,12);ctx.stroke();ctx.restore();}
islands.slice().sort((a,b)=>a.y-b.y).forEach(drawIsland);ports.forEach(drawPort);drawShip();
if(target){const p=project(target.x,target.y),center=project(ship.x,ship.y);if(p.x<40||p.x>w-40||p.y<70||p.y>h-170){let dx=p.x-center.x,dy=p.y-center.y,t=Math.min((w*.36)/Math.max(1,Math.abs(dx)),(h*.30)/Math.max(1,Math.abs(dy)));let x=center.x+dx*t,y=center.y+dy*t;ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(dy,dx));ctx.fillStyle='#ffd18a';ctx.beginPath();ctx.moveTo(11,0);ctx.lineTo(-7,-6);ctx.lineTo(-7,6);ctx.closePath();ctx.fill();ctx.restore();}}
drawMap();}
function drawMap(){mc.clearRect(0,0,210,180);mc.fillStyle='#124757';mc.fillRect(0,0,210,180);mc.strokeStyle='#6da4ad20';for(let i=0;i<210;i+=30){mc.beginPath();mc.moveTo(i,0);mc.lineTo(i,180);mc.stroke();}for(let i=0;i<180;i+=30){mc.beginPath();mc.moveTo(0,i);mc.lineTo(210,i);mc.stroke();}const m=(x,y)=>[105+x/5600*200,90+y/5600*170];islands.forEach(i=>{let p=m(i.x,i.y);mc.beginPath();mc.ellipse(p[0],p[1],i.r/5600*200,i.r/5600*170,0,0,TAU);mc.fillStyle='#648a70';mc.fill();});mc.setLineDash([3,4]);mc.strokeStyle='#b8c7a265';mc.beginPath();let pos=m(ship.x,ship.y);mc.moveTo(...pos);ports.slice(visited).forEach(p=>mc.lineTo(...m(p.x,p.y)));mc.stroke();mc.setLineDash([]);ports.forEach((p,i)=>{const q=m(p.x,p.y);mc.beginPath();mc.arc(q[0],q[1],i===visited?5:3,0,TAU);mc.fillStyle=i<visited?'#82d4b1':i===visited?'#ffd18a':'#acc5c5';mc.fill();});mc.save();mc.translate(...pos);mc.rotate(ship.a);mc.fillStyle='#fff';mc.beginPath();mc.moveTo(0,-6);mc.lineTo(4,5);mc.lineTo(0,3);mc.lineTo(-4,5);mc.closePath();mc.fill();mc.restore();}
addEventListener('keydown',e=>{if(window.strait?.active)return;if(e.target.tagName==='SELECT')return;let k=e.key.toLowerCase();if(sceneIndex>=0){if(k==='escape'){e.preventDefault();if(!e.repeat)leaveIsland();}else if(k===' '&&e.target.tagName!=='BUTTON'){e.preventDefault();if(!e.repeat)window.cinema?.togglePause();}return;}if(k==='m'&&!e.repeat){e.preventDefault();chartOpen?closeChart():openChart();return;}if(chartOpen&&k==='escape'){e.preventDefault();closeChart();return;}if(chartOpen)return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' ','p','escape'].includes(k))e.preventDefault();if((k==='p'||k==='escape')&&!e.repeat){togglePause();return;}keys[k]=true;});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('blur',()=>{Object.keys(keys).forEach(k=>keys[k]=false);if(!paused&&!ended)togglePause();});addEventListener('resize',resize);$('pause').onclick=togglePause;$('reset').onclick=reset;$('resume').onclick=()=>ended?reset():togglePause();$('weather').onchange=()=>{const s=settings[$('weather').value];$('weatherLabel').textContent=$('weather').selectedOptions[0].text;$('wind').textContent=`바람 ${s.wind} kn · 파고 ${s.wave} m`;toast('해상 상태가 바뀌었어요. 바람과 파도에 맞춰 조종하세요.');};document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys[b.dataset.key]=false);});
function drawLandmark(i){const p=project(i.x,i.y,28),z=scale();ctx.save();ctx.translate(p.x,p.y);ctx.scale(z,z);
if(i.type==='lotus'){for(let n=0;n<22;n++){let a=n*2.4,r=35+Math.sqrt(n)*22;ctx.fillStyle='#dba3bc';ctx.beginPath();ctx.ellipse(Math.cos(a)*r,Math.sin(a)*r*.6,7,4,a,0,TAU);ctx.fill();ctx.fillStyle='#fae3b0';ctx.fillRect(Math.cos(a)*r-1,Math.sin(a)*r*.6-1,2,2);}}
if(i.type==='cave'||i.type==='cliff'){for(let n=0;n<5;n++){ctx.fillStyle=n%2?'#6b6260':'#9b8b78';ctx.beginPath();ctx.moveTo(-110+n*42,22);ctx.lineTo(-85+n*42,-95-(n%3)*20);ctx.lineTo(-30+n*42,27);ctx.closePath();ctx.fill();}if(i.type==='cave'){ctx.fillStyle='#222e32';ctx.beginPath();ctx.ellipse(0,6,23,32,0,Math.PI,TAU);ctx.fill();ctx.fillStyle='#e3c17c';ctx.beginPath();ctx.ellipse(0,-5,5,2,0,0,TAU);ctx.fill();}}
if(i.type==='wind'){ctx.strokeStyle='#e4f5da90';ctx.lineWidth=3;for(let n=0;n<3;n++){ctx.beginPath();ctx.ellipse(0,-20-n*15,50+n*25,15+n*12,0,clock*.35+n,clock*.35+n+Math.PI*1.5);ctx.stroke();}}
if(i.type==='temple'||i.type==='home'){ctx.fillStyle='#e2d4b4';ctx.fillRect(-48,-45,96,12);for(let n=0;n<5;n++)ctx.fillRect(-42+n*19,-38,9,45);ctx.fillRect(-52,7,104,9);ctx.fillStyle=i.type==='temple'?'#b4a0bc':'#bc8668';ctx.beginPath();ctx.moveTo(-58,-45);ctx.lineTo(0,-78);ctx.lineTo(58,-45);ctx.closePath();ctx.fill();}
ctx.restore();}
function openChart(){if(window.strait?.active||sceneIndex>=0||chartOpen)return;chartPreviousPause=paused;paused=true;chartOpen=true;Object.keys(keys).forEach(k=>keys[k]=false);$('atlas').hidden=false;selectIsland(Math.min(visited,5));renderAtlas();$('closeAtlas').focus();}
function closeChart(){if(!chartOpen)return;chartOpen=false;paused=chartPreviousPause;$('atlas').hidden=true;$('openAtlas').focus();}
function selectIsland(n){const d=destinations[n];$('islandTitle').textContent=String(n+1).padStart(2,'0')+' · '+d.name;$('islandSubtitle').textContent=d.subtitle;$('islandStory').textContent=d.desc;$('islandStatus').textContent=n<visited?'탐험 완료':n===visited?'현재 목적지 · 원 안에서 3 kn 이하로 2초 정박':'항해 순서 '+(n+1)+' / 6';document.querySelectorAll('.atlas-stop').forEach((b,i)=>{b.classList.toggle('selected',i===n);b.setAttribute('aria-pressed',String(i===n));});}
function renderAtlas(){const c=$('atlasCanvas'),g=c.getContext('2d'),W=1000,H=780;g.clearRect(0,0,W,H);g.fillStyle='#123b49';g.fillRect(0,0,W,H);const m=(x,y)=>[500+x/5600*890,380+y/5600*650];g.strokeStyle='#b6c5b218';g.lineWidth=1;for(let x=55;x<1000;x+=89){g.beginPath();g.moveTo(x,40);g.lineTo(x,720);g.stroke();}for(let y=55;y<740;y+=65){g.beginPath();g.moveTo(45,y);g.lineTo(955,y);g.stroke();}g.strokeStyle='#d5bd8733';g.strokeRect(25,25,950,730);
for(const i of islands){const p=m(i.x,i.y);for(const [factor,col] of [[1.3,'#61b2a32b'],[1.1,'#d6c394'],[1,i.color||'#648774']]){g.beginPath();islandShape(i,i.r*factor,0).forEach((pt,j)=>{let q=m(pt[0],pt[1]);j?g.lineTo(...q):g.moveTo(...q);});g.closePath();g.fillStyle=col;g.fill();}}
g.setLineDash([7,9]);g.strokeStyle='#eacb84a0';g.lineWidth=2;g.beginPath();g.moveTo(...m(-1900,2220));ports.forEach(p=>g.lineTo(...m(p.x,p.y)));g.stroke();g.setLineDash([]);
destinations.forEach((i,n)=>{const p=m(i.x,i.y);g.fillStyle='#092b36';g.beginPath();g.arc(p[0],p[1],17,0,TAU);g.fill();g.fillStyle=n<visited?'#8fdfbd':'#f4d294';g.font='bold 17px Arial';g.textAlign='center';g.fillText(String(n+1),p[0],p[1]+6);g.font='bold 18px Arial';g.fillStyle='#fbedd1';g.fillText(i.name,p[0],p[1]-i.r/5600*650-13);let q=m(ports[n].x,ports[n].y);g.beginPath();g.arc(q[0],q[1],7,0,TAU);g.fillStyle=n===visited?'#ffcf79':n<visited?'#87c8ab':'#729b9d';g.fill();});
const p=m(ship.x,ship.y);g.save();g.translate(...p);g.rotate(ship.a);g.fillStyle='#fff';g.beginPath();g.moveTo(0,-11);g.lineTo(7,9);g.lineTo(0,5);g.lineTo(-7,9);g.closePath();g.fill();g.restore();g.font='14px Arial';g.textAlign='center';g.fillStyle='#e7ece2';g.fillText('내 배',p[0],p[1]+28);g.fillStyle='#d5bf90';g.font='22px Georgia';g.fillText('N',913,67);g.beginPath();g.moveTo(913,80);g.lineTo(906,105);g.lineTo(913,99);g.lineTo(920,105);g.closePath();g.fill();g.font='italic 23px Georgia';g.fillStyle='#98b4ad80';g.fillText('THE WINE-DARK SEA',480,363);g.font='14px Arial';g.fillStyle='#b3c4bd';g.textAlign='left';g.fillText('항해 구역 5.2 × 5.2 km',60,735);}
$('openAtlas').onclick=openChart;$('closeAtlas').onclick=closeChart;mini.onclick=openChart;mini.style.cursor='pointer';$('atlasCanvas').onclick=e=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)*1000/r.width,y=(e.clientY-r.top)*780/r.height;let best=0,dist=Infinity;destinations.forEach((d,i)=>{let v=Math.hypot(x-(500+d.x/5600*890),y-(380+d.y/5600*650));if(v<dist){best=i;dist=v;}});if(dist<100)selectIsland(best);};destinations.forEach((d,i)=>{const b=document.createElement('button');b.className='atlas-stop';b.textContent=String(i+1).padStart(2,'0')+'  '+d.name;b.onclick=()=>selectIsland(i);$('atlasStops').appendChild(b);});$('atlas').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const buttons=Array.from($('atlas').querySelectorAll('button'));const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
const shoreScenes=[{title:'연꽃이 피어난 해안',line:'분홍빛 연꽃 사이로 선원들의 목소리가 사라집니다. 멀리서 누군가 돛을 부릅니다.',atmosphere:'로토파고이 · 짧은 목격'},{title:'동굴에서 깨어난 것',line:'파도보다 큰 발소리. 어둠 속에서 하나의 눈이 떠집니다. 당신은 즉시 배로 돌아갑니다.',atmosphere:'키클롭스의 섬 · 짧은 목격'},{title:'바람의 궁전',line:'구름 사이로 궁전이 나타나고, 갑자기 돛이 팽팽해집니다. 바람이 당신을 다시 바다로 밀어냅니다.',atmosphere:'아이올리아 · 짧은 목격'},{title:'절벽 위의 그림자',line:'붉은 절벽 위로 거대한 그림자가 지나갑니다. 바닷물이 흔들리고, 당신은 조용히 만을 빠져나옵니다.',atmosphere:'텔레필로스 · 짧은 목격'},{title:'숲속의 보랏빛 궁전',line:'안개 사이로 키르케가 모습을 드러냅니다. 그녀가 손을 들자 숲의 불빛이 꺼지고, 장면이 끝납니다.',atmosphere:'아이아이아 · 짧은 목격'},{title:'고향의 불빛',line:'새벽빛 아래 익숙한 항구가 나타납니다. 긴 항해는 아무 말 없이 끝납니다.',atmosphere:'이타카 · 마지막 장면'}];
function enterIsland(index){sceneIndex=index;paused=true;ship.v=0;Object.keys(keys).forEach(k=>keys[k]=false);const story=shoreScenes[index];$('sceneEyebrow').textContent=story.atmosphere;$('sceneTitle').textContent=story.title;$('sceneText').textContent=story.line;$('sceneCount').textContent=String(index+1).padStart(2,'0')+' / 06 · 상륙';$('leaveIsland').textContent=index===5?'영상 종료 후 엔딩':'건너뛰기 →';$('sceneNext').textContent=index===5?'이타카 영상이 끝나면 영화 포스터가 나타납니다.':'다음 목적지 · '+destinations[index+1].name;$('islandScene').hidden=false;document.body.classList.add('ashore');window.cinema?.start(index);if(index!==5)$('leaveIsland').focus();}
function leaveIsland(){if(sceneIndex<0)return;const departing=sceneIndex,finalIsland=departing===5;window.cinema?.stop();sceneIndex=-1;$('islandScene').hidden=true;document.body.classList.remove('ashore');Object.keys(keys).forEach(k=>keys[k]=false);if(finalIsland){showPoster();return;}if(departing===2&&window.strait?.show())return;paused=false;$('pause').textContent='Ⅱ';$('pause').focus();toast('다시 출항하세요. 다음 목적지는 '+(ports[visited]?.name||'이타카')+'입니다.');}
$('leaveIsland').onclick=leaveIsland;function showPoster(){ended=true;paused=true;$('islandScene').hidden=true;document.body.classList.remove('ashore');$('posterTime').textContent=String(Math.floor(elapsed/60)).padStart(2,'0')+':'+String(Math.floor(elapsed%60)).padStart(2,'0');$('posterHull').textContent=Math.ceil(ship.hull)+'%';$('posterEnd').hidden=false;$('posterRestart').focus();} $('posterRestart').onclick=reset;
$('startPromoGame').onclick=()=>{homeOpen=false;$('movieHome').hidden=true;paused=false;last=performance.now();toast('W / ↑ 로 출항하세요. M 키로 오디세이 전체 해도를 펼쳐보세요.');canvas.focus();};
resize();reset();$('startPromoGame').focus();function frame(now){let dt=Math.min(.04,(now-last)/1000||.016);last=now;if(!document.hidden){step(dt);if(sceneIndex<0&&!ended)draw();}requestAnimationFrame(frame);}requestAnimationFrame(frame);
